name: event_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.6.1

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/
        - assets/images/
    fonts:
        - family: Poppins
          fonts:
              - asset: fonts/Poppins-Regular.ttf
              - asset: fonts/Poppins-ExtraLight.ttf
                weight: 200
              - asset: fonts/Poppins-Light.ttf
                weight: 300
              - asset: fonts/Poppins-SemiBold.ttf
                weight: 600
              - asset: fonts/Poppins-Bold.ttf
                weight: 700
              - asset: fonts/Poppins-ExtraBold.ttf
                weight: 800
